name: ci

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Extract metadata (tags, logs) for docker
        id: meta
        uses:  docker/metadata-action@v5
        with: 
          images: dockschon/react-tetris-image
          tags: |
            type=semver,pattern={{version}}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

# on: push

# jobs:
#   build:
#     name: Test
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '14.x'
      # - run: npm install
      # - run: npm test
      # - run: npm run build
